### ISSUE TITLE
万分感谢您的支持，帮助了我们海信电视能使用TVBOX

### ISSUE THREAD

**Issue by wolopo** [Klosw/Box#1]
万分感谢您的支持，帮助了我们海信电视能使用TVBOX

我有个请求不知道行不行，就是tvbox搜索结果后，点击其中之一电视剧链接，都第一个（默认）是【神秘哥哥 放丢失】源，它有擦边的广告，家里有孩子，不太适用，就不敢用了。看看能不能帮我修正（或如何解决），实在感谢，感谢！！！

**Comment by Klosw** [comment]
你换个源不就好了

**Comment by wolopo** [comment]
多谢多谢
